name: Run Unit Tests with Coverage

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI 19 globally
        run: npm install -g @angular/cli@19

      - name: Install system dependencies (Chrome + xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev wget xvfb
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Update devkit to match Angular 19
        working-directory: app-movil
        run: |
          npm install @angular-devkit/build-angular@19.2.8 --save-dev

      - name: Install npm dependencies
        working-directory: app-movil
        run: |
          npm ci || npm install
          npm audit fix --force || true

      - name: Verify Angular version
        working-directory: app-movil
        run: npx ng version

      - name: Run unit tests with coverage
        working-directory: app-movil
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          xvfb-run -a npx ng test --code-coverage --browsers=ChromeHeadlessNoSandbox --watch=false

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app-movil/coverage/
